//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestClient.RemoteService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RemoteService.ISendData")]
    public interface ISendData {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendData/ReceiveFile", ReplyAction="http://tempuri.org/ISendData/ReceiveFileResponse")]
        System.Collections.Generic.Dictionary<string, uint> ReceiveFile(string[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendData/ReceiveFile", ReplyAction="http://tempuri.org/ISendData/ReceiveFileResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, uint>> ReceiveFileAsync(string[] data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISendDataChannel : TestClient.RemoteService.ISendData, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SendDataClient : System.ServiceModel.ClientBase<TestClient.RemoteService.ISendData>, TestClient.RemoteService.ISendData {
        
        public SendDataClient() {
        }
        
        public SendDataClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SendDataClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendDataClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendDataClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.Dictionary<string, uint> ReceiveFile(string[] data) {
            return base.Channel.ReceiveFile(data);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, uint>> ReceiveFileAsync(string[] data) {
            return base.Channel.ReceiveFileAsync(data);
        }
    }
}
